version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16.1
  python:
    docker:
      - image: circleci/python:3.7.9-stretch

jobs:
  generate_release:
    executor: node
    steps:
      - checkout
      - run:
          name: 'Generate Release'
          command: |
            sudo npm i -g @semantic-release/changelog @semantic-release/git semantic-release
            semantic-release

  # run_linter:
  # run_test:

workflows:
  development:
    jobs:
      - run_linter
      - run_test

  production:
    jobs:
      - generate_release